@extends('layouts.master')
@section('title')
    Đăng kí thời khóa biểu
@endsection
@section('css')
    <style>
        .required {
            color: red;
        }

        .select2-selection__rendered {
            padding-top: 6px;
        }

        #formExcel{
            position: relative;
            margin: 0 auto;
            width: 500px;
            height: 200px;
            border: 4px dashed #7b7373;
        }
        #formExcel .form-group p{
            width: 100%;
            height: 100%;
            text-align: center;
            line-height: 200px;
            color: #7b7373;
            font-family: Arial;
        }
        #fileExcel{
            position: absolute;
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            outline: none;
            opacity: 0;
        }
        #uploadEx{
            margin: 0;
            color: #fff;
            background: #16a085;
            border: none;
            width: 100%;
            height: 35px;
            border-radius: 4px;
            border-bottom: 4px solid #117A60;
            transition: all .2s ease;
            outline: none;
            display: none;
        }
        #uploadEx:hover{
            background: #149174;
            color: #0C5645;
        }
        #uploadEx:active{
            border:0;
        }


    </style>
    <style type="text/css">
        @keyframes ldio-w61dkjf0pdd {
            0% { opacity: 1 }
            100% { opacity: 0 }
        }
        .ldio-w61dkjf0pdd div {
            left: 94px;
            top: 48px;
            position: absolute;
            animation: ldio-w61dkjf0pdd linear 1s infinite;
            background: #93dbe9;
            width: 12px;
            height: 24px;
            border-radius: 6px / 12px;
            transform-origin: 6px 52px;
        }.ldio-w61dkjf0pdd div:nth-child(1) {
             transform: rotate(0deg);
             animation-delay: -0.9166666666666666s;
             background: #93dbe9;
         }.ldio-w61dkjf0pdd div:nth-child(2) {
              transform: rotate(30deg);
              animation-delay: -0.8333333333333334s;
              background: #93dbe9;
          }.ldio-w61dkjf0pdd div:nth-child(3) {
               transform: rotate(60deg);
               animation-delay: -0.75s;
               background: #93dbe9;
           }.ldio-w61dkjf0pdd div:nth-child(4) {
                transform: rotate(90deg);
                animation-delay: -0.6666666666666666s;
                background: #93dbe9;
            }.ldio-w61dkjf0pdd div:nth-child(5) {
                 transform: rotate(120deg);
                 animation-delay: -0.5833333333333334s;
                 background: #93dbe9;
             }.ldio-w61dkjf0pdd div:nth-child(6) {
                  transform: rotate(150deg);
                  animation-delay: -0.5s;
                  background: #93dbe9;
              }.ldio-w61dkjf0pdd div:nth-child(7) {
                   transform: rotate(180deg);
                   animation-delay: -0.4166666666666667s;
                   background: #93dbe9;
               }.ldio-w61dkjf0pdd div:nth-child(8) {
                    transform: rotate(210deg);
                    animation-delay: -0.3333333333333333s;
                    background: #93dbe9;
                }.ldio-w61dkjf0pdd div:nth-child(9) {
                     transform: rotate(240deg);
                     animation-delay: -0.25s;
                     background: #93dbe9;
                 }.ldio-w61dkjf0pdd div:nth-child(10) {
                      transform: rotate(270deg);
                      animation-delay: -0.16666666666666666s;
                      background: #93dbe9;
                  }.ldio-w61dkjf0pdd div:nth-child(11) {
                       transform: rotate(300deg);
                       animation-delay: -0.08333333333333333s;
                       background: #93dbe9;
                   }.ldio-w61dkjf0pdd div:nth-child(12) {
                        transform: rotate(330deg);
                        animation-delay: 0s;
                        background: #93dbe9;
                    }
        .loadingio-spinner-spinner-kwnzxy788ab {
            width: 100%;
            height: 100%;

            display: inline-block;
            overflow: hidden;
            background: #f1f2f3;
        }
        .ldio-w61dkjf0pdd {
            width: 200px;
            height: 200px;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
            margin: 0 auto;
            top: 35%;
        }
        .ldio-w61dkjf0pdd div { box-sizing: content-box; }
        /* generated by https://loading.io/ */

        .loading{
            display: none;
            position: fixed;
            top: 0;
            z-index: 9999;
            background-color: rgba(241, 242, 243,0.2);
        }
    </style>
@endsection
@section('script')
@if(session()->get('message'))
    <script>
        toastr.success(@json(session()->get('message')));
    </script>
@endif
<script>
    const qualityWeekSemester = @json(\Session::get('semester_now')['number_weeks']);
</script>
<script src="{{asset('assets/js/registerCalendar.js')}}"></script>
@endsection
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Thời khóa biểu</h1>
                <div class="section-header-breadcrumb">
                    <div class="breadcrumb-item active"><a href="{{route('backend.dashboard')}}">Bảng điều khiển</a>
                    </div>
                    <div class="breadcrumb-item">Đăng kí thời khóa biểu</div>
                </div>
            </div>

            <div class="section-body">
                <h2 class="section-title">Đăng kí</h2>
                <p class="section-lead">
                    {!! isset($weekNow) ? 'Tuần hiện tại: Tuần '.$weekNow : '<span style="color: red">Ngoài thời gian đăng kí !<span>'!!}
                </p>
                <div class="row">
                    <div class="col-12">
                        <div class="card mb-0">
                            <div class="card-body">
                                <ul class="nav nav-pills">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#" id="btnExcel">Nhập Excel</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-12 ">
                        <div class="card">
                            <form method="post" action="{{route('calendar.store')}}" id="formAddEventCalendar">
                                @csrf
                                <div class="row">
                                    <div class="card-body col-4">
                                        <div class="form-group">
                                            <label>Học kì:</label>
                                            <input type="text" class="form-control" disabled
                                                   value="Học kì:{{\Session::get('semester_now')['semester']}} - Năm học:{{\Session::get('semester_now')['school_year']}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Phòng máy:</label>
                                            <select class="js-example-basic-single form-control  select2-input" id="room" name="room">
                                                <option value=""></option>
                                                @foreach($rooms as $room)
                                                    <option value="{{$room['id']}}">{{$room['room_id']}}</option>
                                                @endforeach
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Môn học: <span class="required">(*)</span></label>
                                            <select class="js-example-basic-single form-control  select2-input" id="subject" name="subject">
                                                <option value=""></option>
                                                @foreach($subjects as $subject)
                                                    <option value="{{$subject['id']}}">{{$subject['subject_id'] .' - '.$subject['name']}}</option>
                                                @endforeach
                                            </select>
                                        </div>

                                        <div class="form-group">
                                            <label>Tiết bắt đầu:<span class="required">(*)</span></label>
                                            <input type="number" class="form-control" id="lesson_start" name="lesson_start" min="1"
                                                   max="13" value="{{old('lesson_start')}}">
                                        </div>

                                        <div class="form-group">
                                            <label>Tuần bắt đầu:<span class="required">(*)</span></label>
                                            <input type="number" class="form-control week" id="week_start" name="week_start"
                                                   value="{{old('week_start')}}">
                                        </div>

                                    </div>
                                    <div class="card-body col-4">
                                        <div class="form-group">
                                            <label>Giảng viên:</label>
                                            <input type="text" class="form-control" disabled id="user_name"
                                                   name="user_name" value="{{Auth::user()->full_name}}">
                                        </div>

                                        <div class="form-group">
                                            <label>Lớp: <span class="required">(*)</span></label>
                                            <input type="text" class="form-control" id="class" name="class" value="{{old('class')}}">
                                        </div>

                                        <div class="form-group">
                                            <label>Nhóm môn học: <span class="required">(*)</span></label>
                                            <input type="text" class="form-control" id="group" name="group" value="{{old('group')}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Số tiết: <span class="required">(*)</span></label>
                                            <input type="text" class="form-control" id="lesson_quantity" name="lesson_quantity" value="{{old('lesson_quantity')}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Số tuần:<span class="required">(*)</span></label>
                                            <input type="number" class="form-control week" id="week_quantity" name="week_quantity" required=""
                                                   value="{{old('week_quantity')}}">
                                            <div class="invalid-feedback">
                                                Bạn chưa nhập số tuần
                                            </div>
                                        </div>

                                    </div>
                                    <div class="card-body col-4">
                                        <div class="form-group">
                                            <label>thời gian đăng kí:</label>
                                            <input type="text" class="form-control" disabled id="time" name="time"
                                                   value="{{date('d-m-Y H:m')}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Sĩ số:<span class="required">(*)</span></label>
                                            <input type="text" class="form-control" id="quantity" name="quantity"
                                                   value="{{old('quantity')}}" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Thứ:</label>
                                            <select class="form-control" name="weekDay" id="weekDay">
                                                @for($i=0;$i<7;$i++)
                                                    @if($i==6)
                                                        <option value="{{$i+2}}">Chủ nhật</option>
                                                    @else
                                                        <option value="{{$i+2}}">Thứ {{$i+2}}</option>
                                                    @endif
                                                @endfor
                                            </select>
                                        </div>
                                        <div class="form-group mb-0">
                                            <label>Ghi chú:</label>
                                            <textarea class="form-control" name="note" id="note"
                                                      style="height: 140px">{{old('note')}}</textarea>
                                        </div>

                                    </div>
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label>Chọn tuần học: <span class="required">(*)</span></label>
                                            <select class="js-example-basic-single form-control select2-input" id="weekCheck" name="weekCheck[]"
                                                    style="width: 219px" multiple="multiple">
                                                <option value=""></option>
                                            </select>
                                        </div>
                                    </div>

                                </div>
                                @if($weekNow!=null && Session::get('semester_now') !=null)

                                    @if($weekNow <= \Session::get('semester_now')['number_weeks'])
                                    <div class="card-footer text-right">
                                        <button class="btn btn-primary" id="btnSubmitAddEventCalendar" for="formAddEventCalendar">Đăng kí</button>
                                    </div>
                                    @endif

                                @endif
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


@endsection

@section('loading')
    <div class="container-loading">
        <div class="loadingio-spinner-spinner-kwnzxy788ab loading"><div class="ldio-w61dkjf0pdd">
                <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            </div>
        </div>
    </div>
@endsection

@section('modals')
    <div class="modal fade" id="excelModals" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Nhập Excel</h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="height: 300px">
                    <form id="formExcel" method="" action="">
                        <div class="form-group">
                            <input id="fileExcel" name="excel" type="file" multiple>
                            <p class="file-text">Thả hoặc chọn tệp của bạn tại đây.</p>
                            <button id="uploadEx" type="submit">Tải lên</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
